version: '3.8'

services:
  task-service:
    build: ./taskService
    ports:
      - "5002:5002"
    env_file:
      - ./taskService/.env
    depends_on:
      - mongo
    networks:
      - backend

  user-service:
    build: ./userService
    ports:
      - "5001:5001"
    env_file:
      - ./userService/.env
    depends_on:
      - mongo
    networks:
      - backend

  project-service:
    build: ./projectService
    ports:
      - "5003:5003"
    env_file:
      - ./projectService/.env
    depends_on:
      - mongo
    networks:
      - backend

  comment-service:
    build: ./commentService
    ports:
      - "5004:5004"
    env_file:
      - ./commentService/.env
    depends_on:
      - mongo
    networks:
      - backend

  notification-service:
    build: ./notificationService
    ports:
      - "5005:5005"
    env_file:
      - ./notificationService/.env
    depends_on:
      - mongo
    networks:
      - backend

  search-service:
    build: ./searchService
    ports:
      - "5006:5006"
    env_file:
      - ./searchService/.env
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
